import type { Recipe, Category, Profile } from "@/lib/types";

export const STATIC_CATEGORIES: Category[] = [
  { id: "cat-breakfast", name: "Breakfast", slug: "breakfast", emoji: "\u{1F95E}" },
  { id: "cat-lunch", name: "Lunch", slug: "lunch", emoji: "\u{1F96A}" },
  { id: "cat-dinner", name: "Dinner", slug: "dinner", emoji: "\u{1F35D}" },
  { id: "cat-desserts", name: "Desserts", slug: "desserts", emoji: "\u{1F370}" },
  { id: "cat-baking", name: "Baking", slug: "baking", emoji: "\u{1F950}" },
  { id: "cat-salads", name: "Salads", slug: "salads", emoji: "\u{1F957}" },
  { id: "cat-vegan", name: "Vegan", slug: "vegan", emoji: "\u{1F331}" },
  { id: "cat-drinks", name: "Drinks", slug: "drinks", emoji: "\u{1F964}" },
];

export const STATIC_CREATORS: Profile[] = [
  { id: "u0", username: "chefmox", display_name: "Chef Mox", bio: "Home cook & founder of MOXN.", avatar_url: "https://api.dicebear.com/9.x/adventurer/svg?seed=chefmox", role: "admin", is_private: false, notify_email: true, notify_new_follower: true, notify_new_review: true, created_at: new Date().toISOString() },
  { id: "u1", username: "oliveandthyme", display_name: "Olive & Thyme", bio: "Mediterranean home cooking, mostly plants.", avatar_url: "https://api.dicebear.com/9.x/adventurer/svg?seed=oliveandthyme", role: "creator", is_private: false, notify_email: true, notify_new_follower: true, notify_new_review: true, created_at: new Date().toISOString() },
  { id: "u2", username: "mamasoon", display_name: "Mama Soon", bio: "Korean comfort food, one bowl at a time.", avatar_url: "https://api.dicebear.com/9.x/adventurer/svg?seed=mamasoon", role: "creator", is_private: false, notify_email: true, notify_new_follower: true, notify_new_review: true, created_at: new Date().toISOString() },
  { id: "u3", username: "thefryingdutch", display_name: "The Frying Dutchman", bio: "Crispy, golden, indulgent. Fry guy.", avatar_url: "https://api.dicebear.com/9.x/adventurer/svg?seed=thefryingdutch", role: "creator", is_private: false, notify_email: true, notify_new_follower: true, notify_new_review: true, created_at: new Date().toISOString() },
  { id: "u4", username: "greengoddess", display_name: "Green Goddess", bio: "Salads that don't taste like punishment.", avatar_url: "https://api.dicebear.com/9.x/adventurer/svg?seed=greengoddess", role: "creator", is_private: false, notify_email: true, notify_new_follower: true, notify_new_review: true, created_at: new Date().toISOString() },
  { id: "u5", username: "brunchbae", display_name: "Brunch Bae", bio: "Weekend mornings are a love language.", avatar_url: "https://api.dicebear.com/9.x/adventurer/svg?seed=brunchbae", role: "creator", is_private: false, notify_email: true, notify_new_follower: true, notify_new_review: true, created_at: new Date().toISOString() },
  { id: "u6", username: "smokeandember", display_name: "Smoke & Ember", bio: "Low and slow BBQ from a tiny balcony.", avatar_url: "https://api.dicebear.com/9.x/adventurer/svg?seed=smokeandember", role: "creator", is_private: false, notify_email: true, notify_new_follower: true, notify_new_review: true, created_at: new Date().toISOString() },
];

function cat(slug: string): Category | undefined {
  return STATIC_CATEGORIES.find((c) => c.slug === slug);
}

function auth(slug: string): Profile | undefined {
  return STATIC_CREATORS.find((c) => c.username === slug);
}

function base(slug: string): Omit<Recipe, "id" | "author_id" | "category_id" | "author" | "category" | "avg_rating" | "rating_count"> {
  return {
    title: "",
    slug,
    summary: null,
    description: null,
    image_url: null,
    prep_minutes: null,
    cook_minutes: null,
    servings: null,
    difficulty: null,
    ingredients: [],
    steps: [],
    is_published: true,
    featured: false,
    created_at: new Date().toISOString(),
  };
}

export const STATIC_RECIPES: Recipe[] = [
  { ...base("lemon-herb-roast-chicken"), id: "r1", author_id: "u1", category_id: "cat-dinner", title: "Lemon Herb Roast Chicken", summary: "Golden roast chicken with a bright lemon-herb butter.", description: "A classic roast chicken with a twist — lemon and herb butter under the skin keeps the meat juicy while the skin gets perfectly golden and crisp.", image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&q=80", servings: 4, prep_minutes: 90, cook_minutes: 75, difficulty: "medium", ingredients: ["1 whole chicken","3 lemons","Rosemary","Thyme","Butter","Garlic","Olive oil","Salt"], steps: ["Zest lemons into softened butter with herbs.","Rub under and over the skin.","Roast at 200\u00b0C for 75 mins.","Rest 10 mins, then carve."], featured: true, avg_rating: 4.5, rating_count: 8, author: auth("oliveandthyme")!, category: cat("dinner") },
  { ...base("watermelon-feta-salad"), id: "r2", author_id: "u1", category_id: "cat-salads", title: "Watermelon Feta Salad", summary: "Sweet, salty and fresh \u2014 the ultimate summer bowl.", image_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80", servings: 4, prep_minutes: 15, cook_minutes: 0, difficulty: "easy", ingredients: ["Watermelon","Feta","Mint","Cucumber","Olive oil","Lime"], steps: ["Cube watermelon and cucumber.","Toss with crumbled feta and mint.","Drizzle olive oil and lime."], avg_rating: 4.2, rating_count: 5, author: auth("oliveandthyme")!, category: cat("salads") },
  { ...base("kimchi-fried-rice"), id: "r3", author_id: "u2", category_id: "cat-dinner", title: "Kimchi Fried Rice", summary: "Leftover rice, punchy kimchi and a crispy egg.", image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80", servings: 4, prep_minutes: 20, cook_minutes: 10, difficulty: "easy", ingredients: ["2 cups rice","1 cup kimchi","2 eggs","Spring onion","Sesame oil","Gochujang"], steps: ["Fry kimchi in sesame oil.","Add rice and gochujang, toss.","Top with a crispy fried egg."], featured: true, avg_rating: 4.8, rating_count: 12, author: auth("mamasoon")!, category: cat("dinner") },
  { ...base("bibimbap-bowl"), id: "r4", author_id: "u2", category_id: "cat-lunch", title: "Bibimbap Bowl", summary: "Rainbow vegetables over rice with a chili-sesame sauce.", image_url: "https://images.unsplash.com/photo-1558162199-5ec04b9bf6f8?w=800&q=80", servings: 4, prep_minutes: 35, cook_minutes: 20, difficulty: "medium", ingredients: ["Rice","Spinach","Carrot","Bean sprouts","Egg","Gochujang","Sesame"], steps: ["Blanch and season each veg separately.","Arrange over warm rice.","Top with egg and sauce."], avg_rating: 4.3, rating_count: 6, author: auth("mamasoon")!, category: cat("lunch") },
  { ...base("crispy-churros"), id: "r5", author_id: "u3", category_id: "cat-desserts", title: "Crispy Churros", summary: "Cinnamon-sugar pillows with molten centers.", image_url: "https://images.unsplash.com/photo-1624377632654-7a5a9b3b0d4?w=800&q=80", servings: 4, prep_minutes: 40, cook_minutes: 15, difficulty: "medium", ingredients: ["Water","Butter","Flour","Eggs","Cinnamon","Sugar","Oil"], steps: ["Boil water and butter, add flour.","Pipe into hot oil, fry golden.","Toss in cinnamon sugar."], featured: true, avg_rating: 4.6, rating_count: 9, author: auth("thefryingdutch")!, category: cat("desserts") },
  { ...base("fluffy-buttermilk-pancakes"), id: "r6", author_id: "u3", category_id: "cat-breakfast", title: "Fluffy Buttermilk Pancakes", summary: "Tall, cloud-like stacks for slow mornings.", image_url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80", servings: 4, prep_minutes: 25, cook_minutes: 10, difficulty: "easy", ingredients: ["Flour","Buttermilk","Eggs","Baking powder","Butter","Maple"], steps: ["Whisk wet and dry separately.","Fold together, rest 10 mins.","Cook on a buttered griddle."], avg_rating: 4.1, rating_count: 7, author: auth("thefryingdutch")!, category: cat("breakfast") },
  { ...base("rainbow-buddha-bowl"), id: "r7", author_id: "u4", category_id: "cat-vegan", title: "Rainbow Buddha Bowl", summary: "Roasted veg, chickpeas and tahini over fluffy rice.", image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80", servings: 4, prep_minutes: 35, cook_minutes: 25, difficulty: "easy", ingredients: ["Rice","Chickpeas","Sweet potato","Broccoli","Tahini","Lemon"], steps: ["Roast veg and chickpeas.","Cook rice.","Whisk tahini dressing, assemble."], featured: true, avg_rating: 4.4, rating_count: 10, author: auth("greengoddess")!, category: cat("vegan") },
  { ...base("crunchy-garden-spring-salad"), id: "r8", author_id: "u4", category_id: "cat-salads", title: "Crunchy Garden Spring Salad", summary: "Peas, radish and cucumber with a lemony dressing.", image_url: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=800&q=80", servings: 4, prep_minutes: 15, cook_minutes: 0, difficulty: "easy", ingredients: ["Peas","Radish","Cucumber","Lettuce","Lemon","Olive oil"], steps: ["Shave radish.","Toss with greens.","Dress with lemon and oil."], avg_rating: 3.9, rating_count: 4, author: auth("greengoddess")!, category: cat("salads") },
  { ...base("sunrise-avocado-toast"), id: "r9", author_id: "u5", category_id: "cat-breakfast", title: "Sunrise Avocado Toast", summary: "Crispy sourdough, smashed avocado, chili and a soft egg.", image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80", servings: 4, prep_minutes: 15, cook_minutes: 5, difficulty: "easy", ingredients: ["Sourdough","Avocado","Eggs","Chili flakes","Olive oil","Salt"], steps: ["Toast the bread.","Smash avocado with salt.","Top with a soft egg."], featured: true, avg_rating: 4.3, rating_count: 11, author: auth("brunchbae")!, category: cat("breakfast") },
  { ...base("sunshine-mango-smoothie"), id: "r10", author_id: "u5", category_id: "cat-drinks", title: "Sunshine Mango Smoothie", summary: "Tropical mango, banana and orange for a bright start.", image_url: "https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800&q=80", servings: 4, prep_minutes: 5, cook_minutes: 0, difficulty: "easy", ingredients: ["Mango","Banana","Orange","Oat milk","Ice"], steps: ["Peel and chop fruit.","Blend with milk and ice."], avg_rating: 4.0, rating_count: 3, author: auth("brunchbae")!, category: cat("drinks") },
  { ...base("smoky-bbq-pulled-jackfruit"), id: "r11", author_id: "u6", category_id: "cat-dinner", title: "Smoky BBQ Pulled Jackfruit", summary: "Slow-cooked jackfruit in a sticky BBQ glaze.", image_url: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80", servings: 4, prep_minutes: 120, cook_minutes: 90, difficulty: "medium", ingredients: ["Jackfruit","BBQ sauce","Onion","Smoked paprika","Bun"], steps: ["Saut\u00e9 onion with paprika.","Add jackfruit and sauce, simmer.","Shred and pile into buns."], avg_rating: 4.2, rating_count: 6, author: auth("smokeandember")!, category: cat("dinner") },
  { ...base("creamy-coconut-lentil-curry"), id: "r12", author_id: "u0", category_id: "cat-vegan", title: "Creamy Coconut Lentil Curry", summary: "Hearty red lentils simmered in coconut milk with warming spices.", image_url: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80", servings: 4, prep_minutes: 40, cook_minutes: 25, difficulty: "easy", ingredients: ["Red lentils","Coconut milk","Onion","Garlic","Curry spices","Spinach"], steps: ["Saut\u00e9 onion and garlic.","Add spices and lentils.","Pour in coconut milk, simmer."], featured: true, avg_rating: 4.7, rating_count: 14, author: auth("chefmox")!, category: cat("vegan") },
  { ...base("rustic-sourdough-loaf"), id: "r13", author_id: "u0", category_id: "cat-baking", title: "Rustic Sourdough Loaf", summary: "A tangy, crusty country loaf with an open crumb.", image_url: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=800&q=80", servings: 4, prep_minutes: 1440, cook_minutes: 45, difficulty: "hard", ingredients: ["Bread flour","Water","Starter","Salt"], steps: ["Autolyse flour and water.","Add starter and salt.","Stretch and fold hourly, bake."], avg_rating: 4.5, rating_count: 8, author: auth("chefmox")!, category: cat("baking") },
  { ...base("honey-cinnamon-banana-bread"), id: "r14", author_id: "u0", category_id: "cat-baking", title: "Honey Cinnamon Banana Bread", summary: "Moist, lightly spiced loaf with a honey glaze.", image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80", servings: 4, prep_minutes: 70, cook_minutes: 50, difficulty: "medium", ingredients: ["Bananas","Eggs","Flour","Sugar","Cinnamon","Honey"], steps: ["Mash bananas.","Mix wet and dry.","Bake, then glaze with honey."], avg_rating: 4.1, rating_count: 9, author: auth("chefmox")!, category: cat("baking") },
  { ...base("molten-chocolate-cake"), id: "r15", author_id: "u0", category_id: "cat-desserts", title: "Molten Chocolate Cake", summary: "Gooey centered chocolate cakes ready in 12 minutes.", image_url: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80", servings: 4, prep_minutes: 20, cook_minutes: 9, difficulty: "medium", ingredients: ["Dark chocolate","Eggs","Butter","Sugar","Flour"], steps: ["Melt chocolate and butter.","Whisk eggs and sugar.","Fold in flour, bake 9 mins."], avg_rating: 4.6, rating_count: 10, author: auth("chefmox")!, category: cat("desserts") },
  { ...base("citrus-quinoa-salad"), id: "r16", author_id: "u1", category_id: "cat-salads", title: "Citrus Quinoa Salad", summary: "Bright, zesty quinoa with orange, herbs and almonds.", image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80", servings: 4, prep_minutes: 25, cook_minutes: 15, difficulty: "easy", ingredients: ["Quinoa","Orange","Parsley","Mint","Almonds","Olive oil"], steps: ["Cook quinoa, cool.","Segment orange.","Toss with herbs and nuts."], avg_rating: 4.2, rating_count: 5, author: auth("oliveandthyme")!, category: cat("salads") },
  { ...base("garden-caprese-sandwich"), id: "r17", author_id: "u0", category_id: "cat-lunch", title: "Garden Caprese Sandwich", summary: "Fresh mozzarella, tomato and basil on ciabatta.", image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&q=80", servings: 4, prep_minutes: 10, cook_minutes: 0, difficulty: "easy", ingredients: ["Ciabatta","Mozzarella","Tomato","Basil","Olive oil","Balsamic"], steps: ["Slice roll.","Layer cheese, tomato, basil.","Drizzle oil and balsamic."], avg_rating: 4.0, rating_count: 4, author: auth("chefmox")!, category: cat("lunch") },
  { ...base("one-pan-tomato-basil-pasta"), id: "r18", author_id: "u0", category_id: "cat-dinner", title: "One-Pan Tomato Basil Pasta", summary: "A 20-minute weeknight pasta bursting with fresh tomato.", image_url: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80", servings: 4, prep_minutes: 25, cook_minutes: 15, difficulty: "easy", ingredients: ["Pasta","Cherry tomatoes","Garlic","Basil","Parmesan","Olive oil"], steps: ["Simmer tomatoes and garlic.","Cook pasta in the sauce.","Toss with basil and parmesan."], avg_rating: 4.3, rating_count: 7, author: auth("chefmox")!, category: cat("dinner") },
  { ...base("cardamom-rose-chai"), id: "r19", author_id: "u0", category_id: "cat-drinks", title: "Cardamom Rose Chai", summary: "Fragrant masala chai with a floral finish.", image_url: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=800&q=80", servings: 4, prep_minutes: 15, cook_minutes: 10, difficulty: "easy", ingredients: ["Milk","Black tea","Cardamom","Ginger","Rose water","Sugar"], steps: ["Simmer spices in water.","Add tea and milk.","Strain, add rose water."], avg_rating: 4.4, rating_count: 8, author: auth("chefmox")!, category: cat("drinks") },
  { ...base("berry-yogurt-parfait"), id: "r20", author_id: "u0", category_id: "cat-desserts", title: "Berry Yogurt Parfait", summary: "Layers of yogurt, granola and summer berries.", image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80", servings: 4, prep_minutes: 8, cook_minutes: 0, difficulty: "easy", ingredients: ["Yogurt","Granola","Strawberries","Blueberries","Honey"], steps: ["Layer yogurt and berries.","Top with granola.","Drizzle honey."], avg_rating: 3.8, rating_count: 3, author: auth("chefmox")!, category: cat("desserts") },
];
